CREATE DATABASE TESTE_DB;

USE TESTE_DB;

CREATE TABLE USERS(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    STATUS INT DEFAULT 0
);